### ISSUE TITLE
Home page sends using to login page even though user is already logged in.

### ISSUE THREAD

**Issue by StefanoFiumara** [StefanoFiumara/Sogeti-Team6-2015#1]
To replicate:
Log in as a user
close site
open site again
you will be at the login page, but you will have "hello <user>        Log Off" in the navigation bar

**Comment by PFStein** [comment]
Fixed by adding site wide authentication. Check commit https://github.com/StefanoFiumara/Sogeti-Team6-2015/commit/e1b48117d704e552eb0dcf997e0d4961d4940ead
